---
- name: Find a process and kill it
  hosts: all
  become: true

  tasks:
    - name: Getting running processes from remote host
      ignore_errors: yes
      shell: "ps -ef | grep '[t]op'|awk '{print $2}'"
      register: running_process
      
    - name: Kill running processes
      ignore_errors: yes
      shell: "kill {{ item }}"
      with_items: "{{ running_process.stdout_lines }}"
