- name: Playbook pour installer et configurer Tomcat
  hosts: all
  become: true
  vars:
    tomcat_version: "10.1.34"
    tomcat_base_url: "https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.34/bin/"
    tomcat_archive: "apache-tomcat-10.1.34.tar.gz"
    tomcat_install_dir: "/opt/tomcat"
    tomcat_service_file: "/etc/systemd/system/tomcat.service"
    tomcat_port: 8080

  tasks:
    - name: Assurer que le répertoire d'installation de Tomcat existe
      ansible.builtin.file:
        path: "{{ tomcat_install_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Télécharger l'archive de Tomcat si elle n'est pas déjà présente
      ansible.builtin.get_url:
        url: "{{ tomcat_base_url }}{{ tomcat_archive }}"
        dest: "{{ tomcat_install_dir }}/{{ tomcat_archive }}"
        mode: '0644'

    - name: Extraire l'archive Tomcat
      ansible.builtin.unarchive:
        src: "{{ tomcat_install_dir }}/{{ tomcat_archive }}"
        dest: "{{ tomcat_install_dir }}"
        remote_src: yes

    - name: Créer le fichier systemd pour Tomcat
      ansible.builtin.copy:
        dest: "{{ tomcat_service_file }}"
        content: |
          [Unit]
          Description=Apache Tomcat
          After=network.target

          [Service]
          Type=forking
          Environment=JAVA_HOME=/usr/lib/jvm/java-11-openjdk
          Environment=CATALINA_HOME={{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}
          Environment=CATALINA_BASE={{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}
          ExecStart={{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}/bin/startup.sh
          ExecStop={{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}/bin/shutdown.sh
          User=root
          Group=root
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Recharger systemd pour enregistrer les modifications
      ansible.builtin.command:
        cmd: systemctl daemon-reload

    - name: Démarrer et activer le service Tomcat
      ansible.builtin.service:
        name: tomcat
        state: started
        enabled: true

    - name: Vérifier que Tomcat est démarré
      ansible.builtin.wait_for:
        host: "{{ ansible_host | default('127.0.0.1') }}"
        port: "{{ tomcat_port }}"
        timeout: 30
        state: started

